In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("UCI_Credit_Card.csv")

In [9]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [12]:
df["Total_Spend"] = df[[
    "BILL_AMT1","BILL_AMT2","BILL_AMT3",
    "BILL_AMT4","BILL_AMT5","BILL_AMT6"
]].sum(axis=1)

In [13]:
df[["Total_Spend"]].head()

   Total_Spend
0       7704.0
1      17077.0
2     101653.0
3     231334.0
4     109339.0

In [14]:
df["Utilization_%"] = df["Total_Spend"] / df["LIMIT_BAL"]

In [15]:
df[["Utilization_%"]].head()

   Utilization_%
0       0.385200
1       0.142308
2       1.129478
3       4.626680
4       2.186780

In [16]:
def segment(u):
    if u < 0.3:
        return "Low"
    elif u <= 0.7:
        return "Medium"
    else:
        return "High"
    
df["Utilization_Segment"] = df["Utilization_%"].apply(segment)

In [17]:
df[["Utilization_%","Utilization_Segment"]].head()

   Utilization_% Utilization_Segment
0       0.385200              Medium
1       0.142308                 Low
2       1.129478                High
3       4.626680                High
4       2.186780                High

In [18]:
df["Total_Payment"] = df[[
    "PAY_AMT1","PAY_AMT2","PAY_AMT3",
    "PAY_AMT4","PAY_AMT5","PAY_AMT6"
]].sum(axis=1)

In [19]:
df[["Total_Payment"]].head()

   Total_Payment
0          689.0
1         5000.0
2        11018.0
3         8388.0
4        59049.0

In [20]:
df["Risk_Flag"] = df["default.payment.next.month"]

In [21]:
df[["Risk_Flag"]].head()

   Risk_Flag
0          1
1          1
2          0
3          0
4          0

In [22]:
df["Avg_Delay"] = df[[
    "PAY_0","PAY_2","PAY_3",
    "PAY_4","PAY_5","PAY_6"
]].mean(axis=1)

df[["Avg_Delay"]].head()

   Avg_Delay
0  -0.333333
1   0.500000
2   0.000000
3   0.000000
4  -0.333333

In [23]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month,Total_Spend,Utilization_%,Utilization_Segment,Total_Payment,Risk_Flag,Avg_Delay
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,1,7704.0,0.385200,Medium,689.0,1,-0.333333
1,2,120000.0,2,2,2,26,-1,2,0,0,...,1000.0,0.0,2000.0,1,17077.0,0.142308,Low,5000.0,1,0.500000
2,3,90000.0,2,2,2,34,0,0,0,0,...,1000.0,1000.0,5000.0,0,101653.0,1.129478,High,11018.0,0,0.000000
3,4,50000.0,2,2,1,37,0,0,0,0,...,1100.0,1069.0,1000.0,0,231334.0,4.626680,High,8388.0,0,0.000000
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,9000.0,689.0,679.0,0,109339.0,2.186780,High,59049.0,0,-0.333333

In [24]:
df.to_csv("final_credit_data.csv", index=False)